build_script:
 - cd openjdk
 - ..\bootstrap-ikvm\javac.exe -g:none -sourcepath sourcepath282 -bootclasspath ..\ikvmstubs.jar @allsources.lst
 - cd ..\
 - git clone https://github.com/jessielesbian/ikvm built-ikvm
 - robocopy /E /MOV /MT:2 /ZB purge-classes built-ikvm >>nul & exit 0
 - cd built-ikvm
 - robocopy /E /MOV /MT:2 /ZB openjdk\rmistubs ..\backup-rmistubs *.class >>nul & exit 0
 - purgeclasses.bat
 - robocopy /E /MOV /MT:2 /ZB ..\backup-rmistubs openjdk\rmistubs *.class >>nul & exit 0
 - cd ..\
 - robocopy /E /MOV /MT:2 /ZB classpath built-ikvm\classpath *.class >>nul & exit 0
 - robocopy /E /MOV /MT:2 /ZB openjdk built-ikvm\openjdk *.class >>nul & exit 0
 - cd built-ikvm
 - nant\nant.exe
 - 7z a -mm=Deflate -mmt=on -mx=9 ..\ikvm-test-build-with-ikvmclass-{version}.zip bin
 - cd ..\
artifacts:
 - path: ikvm-test-build-with-ikvmclass-{version}.zip
   name: ikvm-test-build-with-ikvmclass-{version}
   type: zip
