build_script:
 - cd openjdk
 - ..\bootstrap-ikvm\javac.exe -g:none -sourcepath sourcepath282 -bootclasspath ..\ikvmstubs.jar @allsources.lst
 - cd ..\
 - git clone https://github.com/jessielesbian/ikvm built-ikvm
 - robocopy /E /MOV /MT:2 /ZB purge-classes built-ikvm >>nul & exit 0
 - cd built-ikvm
 - robocopy /E /MOV /MT:2 /ZB openjdk\rmistubs ..\backup-rmistubs *.class >>nul & exit 0
 - purgeclasses.bat
 - robocopy /E /MOV /MT:2 /ZB ..\backup-rmistubs openjdk\rmistubs *.class >>nul & exit 0
 - cd ..\
 - robocopy /E /MOV /MT:2 /ZB classpath built-ikvm\classpath *.class >>nul & exit 0
 - robocopy /E /MOV /MT:2 /ZB openjdk built-ikvm\openjdk *.class >>nul & exit 0
 - cd built-ikvm
 - nant\nant.exe
 - 7z a -mm=Deflate -mmt=on -mx=9 ..\ikvm-test-build.zip bin
 - cd ..\
test_script:
 - appveyor DownloadFile https://altushost-swe.dl.sourceforge.net/project/dacapobench/9.12-bach-MR1/dacapo-9.12-MR1-bach.jar
 - ikvmtest.bat avrora
 - ikvmtest.bat batik
 - ikvmtest.bat eclipse
 - ikvmtest.bat fop
 - ikvmtest.bat h2
 - ikvmtest.bat jython
 - ikvmtest.bat luindex
 - ikvmtest.bat lusearch
 - ikvmtest.bat lusearch-fix
 - ikvmtest.bat pmd
 - ikvmtest.bat sunflow
 - ikvmtest.bat tomcat
 - ikvmtest.bat tradebeans
 - ikvmtest.bat tradesoap
 - ikvmtest.bat xalan
artifacts:
 - path: ikvm-test-build.zip
   name: ikvm-test-build
   type: zip